---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: collections/_posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: collections/_sections
  label: Sections
  create: all
  match: "**/*"
- type: directory
  path: collections/_people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: collections/_forms
  label: Forms
  create: all
  match: "**/*"
- type: directory
  path: collections/_events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: collections/_docs
  label: Docs
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - PAGES_REPO_NWO=shelbybrad/shelbybrad.github.io
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
